import React from 'react';

const productos2 = [{
	id: "1",
        categoria: "busos",
        sexo: "F",
        talla: "M",
        color: "Negro",
        precio: 100000,
        stock: 10,
        descripcion: "Buso negro corto con un corazon en medio de una frecuencia cardiaca.",
        nombre: "Buso corazon",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298204/Moira/mujer/busos/buso03_hjjd4r.jpg"
    },
    {
	id: "2",
        categoria: "busos",
        sexo: "F",
        talla: "S",
        color: "Blanco",
        precio: 110000,
        stock: 5,
        descripcion: "Buso blanco corto con oso pardo, panda y polar.",
        nombre: "Buso osos",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298203/Moira/mujer/busos/buso04_uqtlti.jpg"
    },
    {
	id: "3",
        categoria: "busos",
        sexo: "M",
        talla: "S",
        color: "Verde oscuro",
        precio: 120000,
        stock: 6,
        descripcion: "Buso verde policia",
        nombre: "Buso AP",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298201/Moira/hombre/busos/buso02_nyww5j.jpg"
    },
    {
	id: "4",
        categoria: "busos",
        sexo: "M",
        talla: "M",
        color: "Rosado",
        precio: 90000,
        stock: 3,
        descripcion: "Buso de color rosado",
        nombre: "Buso chick",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298201/Moira/hombre/busos/buso04_lzapk7.jpg"
    },
    {
	id: "5",
        categoria: "busos",
        sexo: "M",
        talla: "L",
        color: "Negro",
        precio: 150000,
        stock: 1,
        descripcion: "Buso color negro marca Nike",
        nombre: "Buso Nike",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298201/Moira/hombre/busos/buso03_oz7dbi.jpg"
    },
    {
	id: "6",
        categoria: "busos",
        sexo: "M",
        talla: "S",
        color: "gris",
        precio: 180000,
        stock: 1,
        descripcion: "Buso gris del diseñador Luis Vuitton",
        nombre: "Buso Luis Vuitton",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298201/Moira/hombre/busos/buso01_xkkcpv.png"
    },
    {
	id: "7",
        categoria: "busos",
        sexo: "M",
        talla: "M",
        color: "gris",
        precio: 50000,
        stock: 3,
        descripcion: "Buso para papá",
        nombre: "Buso I Love Dad",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298201/Moira/hombre/busos/buso05_fpma3o.jpg"
    },
    {
	id: "8",
        categoria: "busos",
        sexo: "F",
        talla: "L",
        color: "Rojo y Negro",
        precio: 140000,
        stock: 10,
        descripcion: "Buso color rojo, negro y franja blanca con letras girl",
        nombre: "Buso chica",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298203/Moira/mujer/busos/buso05_sqy4mw.jpg"
    },
    {
	id: "9",
        categoria: "busos",
        sexo: "F",
        talla: "XL",
        color: "Blanco",
        precio: 60000,
        stock: 2,
        descripcion: "Buso de color blanco para chicas",
        nombre: "Buso blanco",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298203/Moira/mujer/busos/buso02_zahro2.jpg"
    },
    {
	id: "10",
        categoria: "busos",
        sexo: "F",
        talla: "XXL",
        color: "Negro",
        precio: 200000,
        stock: 10,
        descripcion: "Buso de la banda surcoreana BlackPink",
        nombre: "Buso BlackPink",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298203/Moira/mujer/busos/buso01_bol4bk.jpg"
    },
    {
	id: "11",
        categoria: "pantalonetas",
        sexo: "M",
        talla: "S",
        color: "Negro",
        precio: 50000,
        stock: 12,
        descripcion: "Pantaloneta negra para playa",
        nombre: "Pantaloneta playera",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298203/Moira/hombre/pantalonetas/pantaloneta02_kjaxak.jpg"
    },
    {
	id: "12",
        categoria: "pantalonetas",
        sexo: "M",
        talla: "S",
        color: "Amarillo",
        precio: 52000,
        stock: 11,
        descripcion: "Pantaloneta amarilla estampada",
        nombre: "Pantaloneta playera estampada",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298203/Moira/hombre/pantalonetas/pantaloneta03_suc3jf.jpg"
    },
    {
	id: "13",
        categoria: "pantalonetas",
        sexo: "M",
        talla: "M",
        color: "Negro y gris",
        precio: 60000,
        stock: 9,
        descripcion: "Pantaloneta deportiva de color negro y gris",
        nombre: "Pantaloneta deportiva",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298202/Moira/hombre/pantalonetas/pantaloneta01_i4eg0r.jpg"
    },
    {
	id: "14",
        categoria: "shorts",
        sexo: "F",
        talla: "L",
        color: "Gris",
        precio: 55000,
        stock: 8,
        descripcion: "Short de mezclilla para mujer",
        nombre: "Short de mezclilla",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/shorts/short01_rzizw4.jpg"
    },
    {
	id: "15",
        categoria: "shorts",
        sexo: "F",
        talla: "S",
        color: "Rosado",
        precio: 45000,
        stock: 7,
        descripcion: "Shorcito para dormir color rosado",
        nombre: "Shorcito rosa",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/shorts/short02_ea57nx.jpg"
    },
    {
	id: "16",
        categoria: "shorts",
        sexo: "F",
        talla: "L",
        color: "Amarillo",
        precio: 45000,
        stock: 7,
        descripcion: "Shorcito para dormir color amarillo",
        nombre: "Shorcito amarillo",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/shorts/short03_lwvh4i.jpg"
    },
    {
	id: "17",
        categoria: "shorts",
        sexo: "F",
        talla: "L",
        color: "Gris",
        precio: 55000,
        stock: 8,
        descripcion: "Short de mezclilla para mujer",
        nombre: "Short de mezclilla",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/shorts/short01_rzizw4.jpg"
    },
    {
	id: "18",
        categoria: "shorts",
        sexo: "F",
        talla: "S",
        color: "Rosado",
        precio: 45000,
        stock: 7,
        descripcion: "Shorcito para dormir color rosado",
        nombre: "Shorcito rosa",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/shorts/short02_ea57nx.jpg"
    },
    {
	id: "19",
        categoria: "shorts",
        sexo: "F",
        talla: "L",
        color: "Amarillo",
        precio: 45000,
        stock: 7,
        descripcion: "Shorcito para dormir color amarillo",
        nombre: "Shorcito amarillo",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/shorts/short03_lwvh4i.jpg"
    },
    {
	id: "20",
        categoria: "sudaderas",
        sexo: "F",
        talla: "L",
        color: "Azul",
        precio: 65000,
        stock: 8,
        descripcion: "Sudadera deportiva para mujer color azul",
        nombre: "Sudadera Azul",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/sudaderas/sudadera01_rtirko.jpg"
    },
    {
	id: "21",
        categoria: "sudaderas",
        sexo: "F",
        talla: "S",
        color: "Naranja",
        precio: 65000,
        stock: 7,
        descripcion: "Sudadera para dormir de mujer color naranja",
        nombre: "Sudadera naranja",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/sudaderas/sudadera03_pzwema.jpg"
    },
    {
	id: "22",
        categoria: "sudaderas",
        sexo: "F",
        talla: "XL",
        color: "Rosado",
        precio: 45000,
        stock: 5,
        descripcion: "Sudadera deportiva para mujer color rosado",
        nombre: "Sudadera Azul",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/sudaderas/sudadera02_ibka0e.jpg"
    }, 
    {
	id: "23",
        categoria: "sudaderas",
        sexo: "M",
        talla: "S",
        color: "Negro",
        precio: 48000,
        stock: 9,
        descripcion: "Sudadera deportiva marca Adidas",
        nombre: "Sudadera Adidas",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298203/Moira/hombre/sudaderas/sudadera02_xnuk3k.jpg"
    },
    {
	id: "24",
        categoria: "sudaderas",
        sexo: "M",
        talla: "S",
        color: "Negro",
        precio: 60000,
        stock: 4,
        descripcion: "Sudadera deportiva marca Nike para hombre",
        nombre: "Sudadera Nike",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298203/Moira/hombre/sudaderas/sudadera01_pm6xal.jpg"
    },
    {
	id: "25",
        categoria: "sudaderas",
        sexo: "M",
        talla: "XL",
        color: "Verde Oliva",
        precio: 50000,
        stock: 10,
        descripcion: "Sudadera deportiva Nicke",
        nombre: "Sudadera deportiva Nike",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298203/Moira/hombre/sudaderas/sudadera03_kfg5ct.jpg"
    },
    {
	id: "26",
        categoria: "camisetas",
        sexo: "F",
        talla: "S",
        color: "Gris",
        precio: 30000,
        stock: 9,
        descripcion: "Camiseta color gris de Taylor Swift",
        nombre: "Camiseta Taylor Swift",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298204/Moira/mujer/camisetas/camiseta01_jbp2ol.jpg"
    },
    {
	id: "27",
        categoria: "camisetas",
        sexo: "F",
        talla: "M",
        color: "Negro",
        precio: 45000,
        stock: 5,
        descripcion: "Camiseta Brooklyn 76 para dama",
        nombre: "Camiseta Brooklyn",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/camisetas/camiseta08_hjvlc7.jpg"
    },
    {
	id: "28",
        categoria: "camisetas",
        sexo: "F",
        talla: "L",
        color: "Café",
        precio: 48000,
        stock: 6,
        descripcion: "Camiseta color café",
        nombre: "Camiseta Snoopy",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/camisetas/camiseta07_snnoyt.jpg"
    },
    {
	id: "29",
        categoria: "camisetas",
        sexo: "F",
        talla: "XL",
        color: "Gris",
        precio: 32000,
        stock: 2,
        descripcion: "Camiseta para dama gris",
        nombre: "Camiseta Rolling Stones",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298204/Moira/mujer/camisetas/camiseta05_gzokjq.jpg"
    },
    {
	id: "30",
        categoria: "camisetas",
        sexo: "F",
        talla: "XXL",
        color: "Azul cielo",
        precio: 50000,
        stock: 7,
        descripcion: "Camiseta corta para chica con franjas azules",
        nombre: "Camiseta para chica con franjas azules",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298204/Moira/mujer/camisetas/camiseta06_cwqz00.jpg"
    },
    {
	id: "31",
        categoria: "camisetas",
        sexo: "F",
        talla: "S",
        color: "Negro",
        precio: 25000,
        stock: 10,
        descripcion: "Camiseta para chicas",
        nombre: "Camiseta eighteen years",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298204/Moira/mujer/camisetas/camiseta04_bxzmhp.jpg"
    },
    {
	id: "32",
        categoria: "camisetas",
        sexo: "F",
        talla: "M",
        color: "Rosado",
        precio: 60000,
        stock: 5,
        descripcion: "Camiseta ancha Rosa para dama",
        nombre: "Camiseta Aesthetic",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298204/Moira/mujer/camisetas/camiseta02_aae48i.jpg"
    },
    {
	id: "33",
        categoria: "camisetas",
        sexo: "F",
        talla: "L",
        color: "Verde oliva",
        precio: 50000,
        stock: 4,
        descripcion: "Camiseta manga larga",
        nombre: "Camiseta Oliva",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/camisetas/camiseta10_jca1pn.jpg"
    },
    {
	id: "34",
        categoria: "camisetas",
        sexo: "F",
        talla: "XL",
        color: "Rojo",
        precio: 45000,
        stock: 4,
        descripcion: "Camiseta corta manga larga",
        nombre: "Camiseta Vino Tinto",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298205/Moira/mujer/camisetas/camiseta09_ronrkt.jpg"
    },
    {
	id: "35",
        categoria: "camisetas",
        sexo: "F",
        talla: "XXL",
        color: "Negro",
        precio: 23000,
        stock: 10,
        descripcion: "Camiseta negra de empoderamiento femenino",
        nombre: "Camiseta negra WOMEN",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298204/Moira/mujer/camisetas/camiseta03_ktukgp.jpg"
    },
    {
	id: "36",
        categoria: "camisetas",
        sexo: "M",
        talla: "S",
        color: "Gris",
        precio: 25000,
        stock: 5,
        descripcion: "Camiseta de estampado Rayo Mcqueen",
        nombre: "Camiseta Rayo Mcqueen",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298203/Moira/hombre/camisetas/camiseta10_iry4iq.jpg"
    },
    {
	id: "37",
        categoria: "camisetas",
        sexo: "M",
        talla: "L",
        color: "gris",
        precio: 25000,
        stock: 4,
        descripcion: "Camiseta de estampado Marvel",
        nombre: "Camiseta Marvel",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298202/Moira/hombre/camisetas/camiseta09_ioct9i.jpg"
    },
    {
	id: "38",
        categoria: "camisetas",
        sexo: "M",
        talla: "M",
        color: "Negro",
        precio: 45000,
        stock: 8,
        descripcion: "Camiseta militar",
        nombre: "Camiseta EIVIL",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298202/Moira/hombre/camisetas/camiseta06_qrnmol.jpg"
    },
    {
	id: "39",
        categoria: "camisetas",
        sexo: "M",
        talla: "XL",
        color: "Negro",
        precio: 60000,
        stock: 7,
        descripcion: "Camiseta color negro marca Adidas",
        nombre: "Camiseta Adidas",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298202/Moira/hombre/camisetas/camiseta08_ag5d26.jpg"
    },
    {
	id: "40",
        categoria: "camisetas",
        sexo: "M",
        talla: "XXL",
        color: "Rosado claro",
        precio: 60000,
        stock: 8,
        descripcion: "Camiseta grande y ancha",
        nombre: "Camiseta Aesthetic",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298202/Moira/hombre/camisetas/camiseta07_vapwdl.jpg"
    },
    {
	id: "41",
        categoria: "camisetas",
        sexo: "M",
        talla: "S",
        color: "Gris",
        precio: 54000,
        stock: 9,
        descripcion: "Camiseta para hombre gris",
        nombre: "Camiseta Reebok",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298202/Moira/hombre/camisetas/camiseta05_ybzmke.jpg"
    },
    {
	id: "42",
        categoria: "camisetas",
        sexo: "M",
        talla: "L",
        color: "Azul",
        precio: 45000,
        stock: 1,
        descripcion: "Camiseta para hombre azul",
        nombre: "Camiseta Hackett",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298202/Moira/hombre/camisetas/camiseta04_z4p9c5.jpg"
    },
    {
	id: "43",
        categoria: "camisetas",
        sexo: "M",
        talla: "M",
        color: "Blanco",
        precio: 67000,
        stock: 5,
        descripcion: "Camiseta exclusiva Adidas",
        nombre: "Camiseta Adidas blanca",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298202/Moira/hombre/camisetas/camiseta02_fobtpc.jpg"
    },
    {
	id: "44",
        categoria: "camisetas",
        sexo: "M",
        talla: "Xl",
        color: "Negro",
        precio: 67000,
        stock: 6,
        descripcion: "Camiseta exclusiva Adidas",
        nombre: "Camiseta Adias negra",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298202/Moira/hombre/camisetas/camiseta03_rnsmbb.jpg"
    },
    {
	id: "45",
        categoria: "camisetas",
        sexo: "M",
        talla: "XXL",
        color: "Negro",
        precio: 45000,
        stock: 10,
        descripcion: "Camiseta de color negro y estampado de dragón",
        nombre: "Camiseta de Dragón",
        imagen: "https://res.cloudinary.com/ddonlrenm/image/upload/v1668298201/Moira/hombre/camisetas/camiseta01_xqjhme.jpg"
    }]

    export default productos2;